Export model
uclouvain/osis-export pull request #1
Opened 2021-07-07 14:36 UTC by AL9000

2021-07-07 14:54 UTC, SebCorbin commented on models.py
> +    created_at = models.DateTimeField(_("Created at"), auto_now_add=True)
Il va te manquer une FK vers AsyncTask et une autre vers un Document

2021-07-08 08:42 UTC, SebCorbin commented on models/export.py
> +from osis_common.models.document_file import DocumentFile
C'est pas le bon module :)

2021-07-08 08:42 UTC, SebCorbin commented on models/export.py
> +    document_file = models.ForeignKey(DocumentFile, on_delete=models.CASCADE)
Ton document doit pouvoir être nullable

2021-07-08 09:05 UTC, AL9000 commented on models/export.py
> +from osis_common.models.document_file import DocumentFile
Hum, `FileField` depuis osis_document ?

2021-07-09 07:35 UTC, SebCorbin approved these changes

2021-07-09 07:54 UTC, albrugnetti requested changes

2021-07-09 07:54 UTC, albrugnetti commented on models/export.py
> +    async_task = models.ForeignKey(AsyncTask, on_delete=models.CASCADE)
Afin d'éviter un couplage avec le module OSIS-Async, il est préférable d'avoir un uuid nommé job_uuid (qui va faire reference à uuid OSIS-Async ==> Sans en faire une FK)

2021-07-21 16:52 UTC, AL9000 commented on models/export.py
> +    async_task = models.ForeignKey(AsyncTask, on_delete=models.CASCADE)
Je viens de le faire dans ma prochaine PR, je merge celle ci et je t'ajoute en reviewer de la prochaine :)

2021-07-21 16:52 UTC, merged