Template tags and model updates
uclouvain/osis-export pull request #2
Opened 2021-07-21 16:53 UTC by AL9000

2021-07-21 16:55 UTC, AL9000 commented
Je passe la PR en brouillon afin de faire les tests et le README

2021-07-22 08:44 UTC, SebCorbin requested changes

2021-07-22 08:44 UTC, SebCorbin commented on api/serializers.py
> +from rest_framework import serializers
Fichier non utile

2021-07-22 10:45 UTC, AL9000 commented on api/views.py
> +                or AsyncTask._meta.get_field("time_to_live").get_default()
Alors testé, None ne fonctionne pas, je passe donc par passage de kwargs comme tu disais ;) Beaucoup plus propre !

2021-07-22 10:46 UTC, AL9000 commented on templatetags/excel_export.py
> +                "type": ExportTypes.EXCEL.name,
Et n'avoir qu'un seul templatetag : `export` ?
Je m'étais posé la question aussi.

2021-07-23 07:23 UTC, SebCorbin commented on templatetags/excel_export.py
> +                "type": ExportTypes.EXCEL.name,
Comme tu le sens, mais tu peux aussi avoir autant de template tag qu'il n'en faut, sans dupliquer tout la logique de form

2021-07-23 08:58 UTC, albrugnetti approved these changes

2021-07-26 13:44 UTC, merged